
/*******************************************************************************
Code generated by cgenerator, PLATKMframework
*******************************************************************************/
import {useContext, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Toolbar from '@mui/material/Toolbar';
import IconButton from '@mui/material/IconButton';
import Typography from '@mui/material/Typography';
import Menu from '@mui/material/Menu';
import MenuIcon from '@mui/icons-material/Menu';
import Container from '@mui/material/Container';
import Avatar from '@mui/material/Avatar';
import Button from '@mui/material/Button';
import Tooltip from '@mui/material/Tooltip';
import MenuItem from '@mui/material/MenuItem'; 


export const ModelerMenu = () => {

  const navigate = useNavigate();  

  const [anchorElNav, setAnchorElNav]   = useState(null);
  const [anchorElUser, setAnchorElUser] = useState(null); 

  const handleOpenUserMenu = (event) => {
    setAnchorElUser(event.currentTarget);
  };

  const handleSubMenu = (event, path, code) => {
    event.preventDefault(); 
       navigate(path  , {
        replace: true
    });     
  };
 
  return (
    <>
      <div>
        <AppBar position="sticky" style={{height:'60px'}}>
          <Container maxWidth="x4">
            <Toolbar disableGutters style={{fontSize:'1.0em'}}>
              <div style={{fontSize:'1.0em'}}>Stock</div>  
              <Box sx={{ flexGrow: 1, display: { xs: 'none', md: 'flex', height:'70px' } }} >
                <Button key="boton_menu_entity-relationship"  style={{fontSize:'0.8em', textTransform:'none'}}
                      onClick={(event)=>handleSubMenu(event, "/modeler/entities", "")}  sx={{ my: 2, color: 'white', display: 'block',  }}>Entity Relationship
                </Button>
                <Button key="boton_menu_sequence"  style={{fontSize:'0.8em', textTransform:'none'}}
                      onClick={(event)=>handleSubMenu(event, "/modeler/sequence", "")}  sx={{ my: 2, color: 'white', display: 'block',  }}>Sequence
                </Button>
                <Button key="boton_menu_bpmn"  style={{fontSize:'0.8em', textTransform:'none'}}
                      onClick={(event)=>handleSubMenu(event, "/modeler/bpmn", "")}  sx={{ my: 2, color: 'white', display: 'block',  }}>BPMN
                </Button>
                <Button key="boton_menu_navigation"  style={{fontSize:'0.8em', textTransform:'none'}}
                      onClick={(event)=>handleSubMenu(event, "/modeler/navigation", "")}  sx={{ my: 2, color: 'white', display: 'block',  }}>Navigation
                </Button>
                <Button key="boton_menu_menu"  style={{fontSize:'0.8em', textTransform:'none'}}
                      onClick={(event)=>handleSubMenu(event, "/modeler/menu", "")}  sx={{ my: 2, color: 'white', display: 'block',  }}>Menu
                </Button>
                <Button key="boton_menu_organization_chart"  style={{fontSize:'0.8em', textTransform:'none'}}
                      onClick={(event)=>handleSubMenu(event, "/modeler/organizationchart", "")}  sx={{ my: 2, color: 'white', display: 'block',  }}>Organization Chart
                </Button>
              </Box>
              <Box sx={{ flexGrow: 0 }} style={{fontSize:'0.7em', marginRight:'20px'}}> 
              </Box>
              <Box sx={{ flexGrow: 0 }} style={{fontSize:'0.7em'}}> 
                <Tooltip title="opciones de usuario">
                  <IconButton onClick={handleOpenUserMenu} sx={{ p: 0 }}>
                    <Avatar alt="Remy Sharp" src="/src/assets/images/avatar.jpg" />  
                  </IconButton>
                </Tooltip> 
              </Box>
            </Toolbar> 
          </Container>
        </AppBar>  
      </div>   
    </>
  )
}

